<?php

global $_LANG;


$_LANG['yjpay'] 		= '易极付';
$_LANG['yjpay_desc'] 	= '易极付(https://www.yiji.com/) 是国内先进跨境的网上支付平台。';
$_LANG['yjpay_submit'] 	= '使用易极付支付';


$_LANG['yjpay_cfg_merchant_name'] 	= '商家名称';
$_LANG['yjpay_cfg_merchant_email'] 	= '商家邮箱';
$_LANG['yjpay_cfg_partner_id'] 		= '合作商家号';
$_LANG['yjpay_cfg_secret_key'] 		= '商家安全码';

$_LANG['yjpay_cfg_debug']		= '调试模式?';
$_LANG['yjpay_cfg_debug_range'] = array(0 => '否','1' => '是');

$_LANG['yjpay_cfg_currency'] = '结算货币';
$_LANG['yjpay_cfg_currency_range'] = array(
    'CNY' => '人民币',
    'USD' => '美元',
    'JPY' => '日元'
);

// 支付方式
$_LANG['yjpay_cfg_currency'] = '结算货币';
$_LANG['yjpay_cfg_currency_range'] = array(
    'CNY' => '人民币',
    'USD' => '美元',
    'JPY' => '日元'
);


$_LANG['yjpay_errors'] = array(
	'order_empty' 		=> '指定订单已完成支付或不是使用易极付支付。',
	'number_empty' 		=> '信用卡卡号不能为空',
	'holder_empty' 		=> '持卡人姓名不能为空',
	'expired_empty' 	=> '过期时间不能为空',
	'cvv_empty'			=> '安全码不能为空',
	
	'country_empty'		=> '账单国家不能为空',
	'state_empty'		=> '账单省/州不能为空',
	'city_empty'		=> '账单城市不能为空',
	'address_empty'		=> '账单街道不能为空',
	'zipcode_empty' 	=> '账单邮编不能为空',
	'email_empty'		=> '账单对应邮箱不能为空',
	'phone_empty'		=> '账单对应电话不能为空',
		
	'number_invalid'	=> '信用卡无效',
	'email_format'		=> '账单邮箱格式不正确',
	'cvv_format'		=> '安全码格式不正确',
	
	'refund'			=> '订单还没有完成支付，或已经完成退款.'
);


$_LANG['yjpay_page'] = array(
	'page_title' 	=> '易极付-跨境支付平台',
	
	'order_total' 	=> '订单总价:',
    'order_no'		=> '订单号:',
	
    'card_title' 	=> '信用卡信息',
    'card_info' 	=> '易极付支付使用以下信用卡:',
	
    'number' 		=> '<span class="required">*</span>卡号:',
    'holder' 		=> '<span class="required">*</span>持卡人:',
    'expired_date' 	=> '<span class="required">*</span>过期时间:',
    'security_code' => '<span class="required">*</span>安全码:',
	
    'billing_title' => '账单地址',
    'country' 		=> '<span class="required">*</span>国家:',
    'state' 		=> '<span class="required">*</span>省/州:',
    'city' 			=> '<span class="required">*</span>城市:',
    'address' 		=> '<span class="required">*</span>街道:',
	
    'post_code' 	=> '<span class="required">*</span>邮编:',
    'email' 		=> '<span class="required">*</span>电子邮件:',
    'phone_number' 	=> '<span class="required">*</span>电话号码:',

    'submit' => '立即支付'
);

$_LANG['yjpay_refund'] = array(
	'empty' 		=> '订单错误或已经退款',
	'page_title'	=> '退款',
	'summary'		=> '根据结算银行的规则，如果支持是支付当天24小时前，只允许取消订单，不允许部分退款。',
	'amountLoc'		=> '交易金额',
	'tradeTime'		=> '交易时间',
	'usableRefundMoney' => '已退款',
	'refund_money'		=> '退款金额',
	'note'				=> '退款说明',
	
	'refund_button'		=> '退款',
	'cancel_button'		=> '撤销订单',
	'reback'			=> '返回',
	
	'refund_money_empty'  => '退款金额不能为空',
	'refund_money_format' => '退款金额格式不正确'
);


$_LANG['yjpay_authorize'] = array(
	'empty' 		=> '订单错误或当前订单已处理预授权',
	'page_title'	=> '预授权',
	'summary'		=> '当前支付存在安全风险，请确认是否完成订单',
	'amountLoc'		=> '交易金额',
	'tradeTime'		=> '交易时间',
	'note'			=> '授权说明',
	
	'allow_button'		=> '接受交易',
	'deny_button'		=> '拒绝交易',
	'reback'			=> '返回',
	
	'authorize_empty'  => '预授权说明不能为空'
);



$_LANG['yjpay_wait_notify'] = <<<EOF
	提交支付，正在等待完成.<script type="text/javascript" src="yjpay.php?order_sn=%s"></script>
EOF;

$_LANG['yjpay_pay_success'] = <<<EOF
	支付成功: <a href="yjpay.php?order_sn=%s&act=refund">申请退款</a>
EOF;

$_LANG['yjpay_pay_fail'] = <<<EOF
	支付失败，当前订单被拒付.
EOF;

$_LANG['yjpay_wait_authorize'] = <<<EOF
	当前支付存在风险，需要预付权(%s): <a href="yjpay.php?order_sn=%s&act=authorize">授权</a>
EOF;

$_LANG['yjpay_refund_success'] = <<<EOF
	<span style="color:#EE0000;">退款(%s):%s</span>
EOF;

$_LANG['yjpay_refund_fail'] = <<<EOF
	<span style="color:#EE0000;">退款失败:%s</span>
EOF;


$_LANG['yjpay_authorize_success'] = <<<EOF
	<span style="color:#EE0000;">处理预授权(%s):%s</span>
EOF;

$_LANG['yjpay_authorize_fail'] = <<<EOF
	处理预授权失败:%s
EOF;

$_LANG['yjpay_countries'] = array(
    'ALB' => '阿尔巴尼亚',
    'DZA' => '阿尔及利亚',
    'AFG' => '阿富汗',
    'ARG' => '阿根廷',
    'ARE' => '阿闻酋',
    'ABW' => '阿鲁巴',
    'OMN' => '阿曼',
    'AZE' => '阿塞拜疆',
    'EGY' => '埃及',
    'ETH' => '埃塞俄比亚',
    'IRL' => '爱尔兰',
    'EST' => '爱沙尼亚',
    'AND' => '安道尔',
    'AGO' => '安哥拉',
    'AIA' => '安圭拉',
    'ATG' => '安提瓜和巴布达',
    'AUT' => '奥地利',
    'AUS' => '澳大利亚',
    'MAC' => '澳门',
    'BRB' => '巴巴多斯',
    'PNG' => '巴布亚新几内亚',
    'BHS' => '巴哈马',
    'PAK' => '巴基斯坦',
    'PRY' => '巴拉圭',
    'PSE' => '巴勒斯坦',
    'BHR' => '巴林',
    'PAN' => '巴拿马',
    'BRA' => '巴西',
    'BLR' => '白俄罗斯',
    'BMU' => '百慕大',
    'BGR' => '保加利亚',
    'MNP' => '北马里亚纳',
    'PLW' => '帕劳',
    'BEN' => '贝宁',
    'BEL' => '比利时',
    'ISL' => '冰岛',
    'PRI' => '波多黎各',
    'POL' => '波兰',
    'BOL' => '玻利维亚',
    'BIH' => '波斯尼亚和黑塞哥维那',
    'BWA' => '博茨瓦纳',
    'BLZ' => '伯利兹',
    'BTN' => '不丹',
    'BFA' => '布基纳法索',
    'BDI' => '布隆迪',
    'BVT' => '布维岛',
    'PRK' => '朝鲜',
    'GNQ' => '赤道几内亚',
    'DNK' => '丹麦',
    'DEU' => '德国',
    'TMP' => '东帝汶',
    'TGO' => '多哥',
    'DOM' => '多米尼加共和国',
    'DMA' => '多米尼克',
    'RUS' => '俄罗斯联邦',
    'ECU' => '厄瓜多尔',
    'ERI' => '厄立特里亚',
    'FRA' => '法国',
    'FRO' => '法罗群岛',
    'PYF' => '法属波利尼西亚',
    'GUF' => '法属圭亚那',
    'ATF' => '法属南部领土',
    'VAT' => '梵蒂冈',
    'PHL' => '菲律宾',
    'FJI' => '斐济',
    'FIN' => '芬兰',
    'CPV' => '佛得角',
    'GMB' => '冈比亚',
    'COD' => '刚果（金）',
    'COG' => '刚果（布）',
    'COL' => '哥伦比亚',
    'CRI' => '哥斯达黎加',
    'GRD' => '格林纳达',
    'GRL' => '格陵兰',
    'GEO' => '格鲁吉亚',
    'CUB' => '古巴',
    'GLP' => '瓜德罗普',
    'GUM' => '关岛',
    'GUY' => '圭亚那',
    'KAZ' => '哈萨克斯坦',
    'HTI' => '海地',
    'KOR' => '韩国',
    'NLD' => '荷兰',
    'ANT' => '荷属安的列斯',
    'HMD' => '赫德岛和麦克唐纳岛',
    'HND' => '洪都拉斯',
    'KIR' => '基里巴斯',
    'DJI' => '吉布提',
    'KGZ' => '吉尔吉斯斯坦',
    'GIN' => '几内亚',
    'GNB' => '几内亚比绍',
    'CAN' => '加拿大',
    'GHA' => '加纳',
    'GAB' => '加蓬',
    'KHM' => '柬埔寨',
    'CZE' => '捷克',
    'ZWE' => '津巴布韦',
    'CMR' => '喀麦隆',
    'QAT' => '卡塔尔',
    'CYM' => '开曼群岛',
    'CCK' => '科科斯(基林)群岛',
    'COM' => '科摩罗',
    'CIV' => '科特迪瓦',
    'KWT' => '科威特',
    'HRV' => '克罗地亚',
    'KEN' => '肯尼亚',
    'COK' => '库克群岛',
    'LVA' => '拉脱维亚',
    'LSO' => '莱索托',
    'LAO' => '老挝',
    'LBN' => '黎巴嫩',
    'LBR' => '利比里亚',
    'LBY' => '利比亚',
    'LTU' => '立陶宛',
    'LIE' => '列支敦士登',
    'REU' => '留尼汪',
    'LUX' => '卢森堡',
    'RWA' => '卢旺达',
    'ROM' => '罗马尼亚',
    'MDG' => '马达加斯加',
    'MLT' => '马耳他',
    'MDV' => '马尔代夫',
    'FLK' => '福克兰群岛（马尔维纳斯群岛）',
    'MWI' => '马拉维',
    'MYS' => '马来西亚',
    'MLI' => '马里',
    'MKD' => '前南马其顿',
    'MHL' => '马绍尔群岛',
    'MTQ' => '马提尼克',
    'MYT' => '马约特',
    'MUS' => '毛里求斯',
    'MRT' => '毛里塔尼亚',
    'USA' => '美国',
    'ASM' => '美属萨摩亚',
    'UMI' => '美国本土外小岛屿',
    'VIR' => '美属维尔京群岛',
    'MNG' => '蒙古',
    'MSR' => '蒙特塞拉特',
    'BGD' => '孟加拉国',
    'PER' => '秘鲁',
    'FSM' => '密克罗尼西亚联邦',
    'MMR' => '缅甸',
    'MDA' => '摩尔多瓦',
    'MAR' => '摩洛哥',
    'MCO' => '摩纳哥',
    'MOZ' => '莫桑比克',
    'MEX' => '墨西哥',
    'NAM' => '纳米比亚',
    'ZAF' => '南非',
    'ATA' => '南极洲',
    'SGS' => '南乔治亚岛和南桑德韦奇岛',
    'NRU' => '瑙鲁',
    'NPL' => '尼泊尔',
    'NIC' => '尼加拉瓜',
    'NER' => '尼日尔',
    'NGA' => '尼日利亚',
    'NIU' => '纽埃',
    'NOR' => '挪威',
    'NFK' => '诺福克岛',
    'PCN' => '皮特凯恩',
    'PRT' => '葡萄牙',
    'JPN' => '日本',
    'SWE' => '瑞典',
    'CHE' => '瑞士',
    'SLV' => '萨尔瓦多',
    'SLE' => '塞拉利昂',
    'SEN' => '塞内加尔',
    'CYP' => '塞浦路斯',
    'SYC' => '塞舌尔',
    'SAU' => '沙竺阿拉伯',
    'CXR' => '圣诞岛',
    'STP' => '圣多美和普林西比',
    'SHN' => '圣赫勒拿',
    'KNA' => '圣基茨和尼维斯',
    'LCA' => '圣卢西亚',
    'SMR' => '圣马力诺',
    'SPM' => '圣皮埃尔和密克隆',
    'VCT' => '圣文森特和格林纳丁斯',
    'LKA' => '斯里兰卡',
    'SVK' => '斯洛伐克',
    'SVN' => '斯洛文尼亚',
    'SJM' => '斯瓦尔巴岛和扬马延岛',
    'SWZ' => '斯威士兰',
    'SDN' => '苏丹',
    'SUR' => '苏里南',
    'SOM' => '索马里',
    'SLB' => '所罗门群岛',
    'TJK' => '塔吉克斯坦',
    'THA' => '泰国',
    'TZA' => '坦桑尼亚',
    'TON' => '汤加',
    'TCA' => '特克斯科斯群岛',
    'TTO' => '特立尼达和多巴哥',
    'TUN' => '突尼斯',
    'TUV' => '图瓦卢',
    'TUR' => '土耳其',
    'TKM' => '土库曼斯坦',
    'TKL' => '托克劳',
    'WLF' => '瓦利斯和富图纳',
    'VUT' => '瓦努阿图',
    'GTM' => '危地马拉',
    'VEN' => '委内瑞拉',
    'BRN' => '文莱',
    'UGA' => '乌干达',
    'UKR' => '乌克兰',
    'URY' => '乌拉圭',
    'UZB' => '乌兹别克斯坦',
    'ESP' => '西班牙',
    'ESH' => '西撒哈拉',
    'WSM' => '萨摩亚',
    'GRC' => '希腊',
    'HKG' => '香港',
    'SGP' => '新加坡',
    'NCL' => '新喀里多尼亚',
    'NZL' => '新西兰',
    'HUN' => '匈牙利',
    'SYR' => '叙利亚',
    'JAM' => '牙买加',
    'ARM' => '亚美尼亚',
    'YEM' => '也门',
    'IRQ' => '伊拉克',
    'IRN' => '伊朗',
    'ISR' => '以色列',
    'ITA' => '意大利',
    'IND' => '印度',
    'IDN' => '印度尼西亚',
    'GBR' => '英国',
    'VGB' => '英属维尔京群岛',
    'IOT' => '英属印度洋领地',
    'JOR' => '约旦',
    'VNM' => '越南',
    'ZMB' => '赞比亚',
    'TCD' => '乍得',
    'GIB' => '直布罗陀',
    'CHL' => '智利',
    'CAF' => '中非',
    'CHN' => '中国',
    'TWN' => '中国台湾',
    'SRB' => '塞尔维亚',
    'MNE' => '黑山'
);

$_LANG['yjpay_ccode'] = array_flip($_LANG['yjpay_countries']);


/*

$_LANG['esypay_countries'] = array(
    'ALB' => '阿尔巴尼亚 Albania',
    'DZA' => '阿尔及利亚 Algeria',
    'AFG' => '阿富汗 Afghanistan',
    'ARG' => '阿根廷 Argentina',
    'ARE' => '阿闻酋 United Arab Emirates',
    'ABW' => '阿鲁巴 Aruba',
    'OMN' => '阿曼 Oman',
    'AZE' => '阿塞拜疆 Azerbaijan',
    'EGY' => '埃及 Egypt',
    'ETH' => '埃塞俄比亚 Ethiopia',
    'IRL' => '爱尔兰 Ireland',
    'EST' => '爱沙尼亚 Estonia',
    'AND' => '安道尔 Andorra',
    'AGO' => '安哥拉 Angola',
    'AIA' => '安圭拉 Anguilla',
    'ATG' => '安提瓜和巴布达 Antigua and Barbuda',
    'AUT' => '奥地利 Austria',
    'AUS' => '澳大利亚 Australia',
    'MAC' => '澳门 Macau',
    'BRB' => '巴巴多斯 Barbados',
    'PNG' => '巴布亚新几内亚 Papua New Guinea',
    'BHS' => '巴哈马 Bahamas',
    'PAK' => '巴基斯坦 Pakistan',
    'PRY' => '巴拉圭 Paraguay',
    'PSE' => '巴勒斯坦 Palestine',
    'BHR' => '巴林 Bahrain',
    'PAN' => '巴拿马 Panama',
    'BRA' => '巴西 Brazil',
    'BLR' => '白俄罗斯 Belarus',
    'BMU' => '百慕大 Bermuda',
    'BGR' => '保加利亚 Bulgaria',
    'MNP' => '北马里亚纳 Northern Marianas',
    'PLW' => '帕劳 Palau',
    'BEN' => '贝宁 Benin',
    'BEL' => '比利时 Belgium',
    'ISL' => '冰岛 Iceland',
    'PRI' => '波多黎各 Puerto Rico',
    'POL' => '波兰 Poland',
    'BOL' => '玻利维亚 Bolivia',
    'BIH' => '波斯尼亚和黑塞哥维那 Bosnia and Herzegovina',
    'BWA' => '博茨瓦纳 Botswana',
    'BLZ' => '伯利兹 Belize',
    'BTN' => '不丹 Bhutan',
    'BFA' => '布基纳法索 Burkina Faso',
    'BDI' => '布隆迪 Burundi',
    'BVT' => '布维岛 Bouvet Island',
    'PRK' => '朝鲜 Korea,Democratic People\'s Republic of',
    'GNQ' => '赤道几内亚 Equatorial Guinea',
    'DNK' => '丹麦 Denmark',
    'DEU' => '德国 Germany',
    'TMP' => '东帝汶 East Timor',
    'TGO' => '多哥 Togo',
    'DOM' => '多米尼加共和国 Dominican Republic',
    'DMA' => '多米尼克 Dominica',
    'RUS' => '俄罗斯联邦 Russia Federation',
    'ECU' => '厄瓜多尔 Ecuador',
    'ERI' => '厄立特里亚 Eritrea',
    'FRA' => '法国 France',
    'FRO' => '法罗群岛 Faroe Islands',
    'PYF' => '法属波利尼西亚 French Polynesia',
    'GUF' => '法属圭亚那 French Guiana',
    'ATF' => '法属南部领土 French Southern Territo - ries',
    'VAT' => '梵蒂冈 Vatican',
    'PHL' => '菲律宾 Philippines',
    'FJI' => '斐济 Fiji',
    'FIN' => '芬兰 Finland',
    'CPV' => '佛得角 Cape Verde',
    'GMB' => '冈比亚Gambia',
    'COD' => '刚果（金）Congo, the Democratic Republic of the',
    'COG' => '刚果（布） Congo',
    'COL' => '哥伦比亚 Colombia',
    'CRI' => '哥斯达黎加 Costa Rica',
    'GRD' => '格林纳达 Grenada',
    'GRL' => '格陵兰 Greenland',
    'GEO' => '格鲁吉亚 Georgia',
    'CUB' => '古巴 Cuba',
    'GLP' => '瓜德罗普 Guadeloupe',
    'GUM' => '关岛 Guam',
    'GUY' => '圭亚那 Guyana',
    'KAZ' => '哈萨克斯坦 Kazakhstan',
    'HTI' => '海地 Haiti',
    'KOR' => '韩国 Korea,Republic of',
    'NLD' => '荷兰 Netherlands',
    'ANT' => '荷属安的列斯 Netherlands Antilles',
    'HMD' => '赫德岛和麦克唐纳岛 Heard islands and Mc Donald Islands',
    'HND' => '洪都拉斯 Honduras',
    'KIR' => '基里巴斯 Kiribati',
    'DJI' => '吉布提 Djibouti',
    'KGZ' => '吉尔吉斯斯坦 Kyrgyzstan',
    'GIN' => '几内亚 Guinea',
    'GNB' => '几内亚比绍 Guine - bissau',
    'CAN' => '加拿大 Canada',
    'GHA' => '加纳 Ghana',
    'GAB' => '加蓬 Gabon',
    'KHM' => '柬埔寨 Cambodia',
    'CZE' => '捷克 Czech Repoublic',
    'ZWE' => '津巴布韦 Zimbabwe',
    'CMR' => '喀麦隆 Cameroon',
    'QAT' => '卡塔尔 Qatar',
    'CYM' => '开曼群岛 Cayman Islands',
    'CCK' => '科科斯(基林)群岛 Cocos(Keeling) Islands',
    'COM' => '科摩罗 Comoros',
    'CIV' => '科特迪瓦 Cote d\'Ivoire',
    'KWT' => '科威特 Kuwait',
    'HRV' => '克罗地亚 Croatia',
    'KEN' => '肯尼亚 Kenya',
    'COK' => '库克群岛 Cook Islands',
    'LVA' => '拉脱维亚 Latvia',
    'LSO' => '莱索托 Lesotho',
    'LAO' => '老挝 Lao',
    'LBN' => '黎巴嫩 Lebanon',
    'LBR' => '利比里亚 Liberia',
    'LBY' => '利比亚 Libya',
    'LTU' => '立陶宛 Lithuania',
    'LIE' => '列支敦士登 Liechtenstein',
    'REU' => '留尼汪 Reunion',
    'LUX' => '卢森堡 Luxembourg',
    'RWA' => '卢旺达 Rwanda',
    'ROM' => '罗马尼亚 Romania',
    'MDG' => '马达加斯加 Madagascar',
    'MLT' => '马耳他 Malta',
    'MDV' => '马尔代夫 Maldives',
    'FLK' => '福克兰群岛（马尔维纳斯群岛）Falkland Islands',
    'MWI' => '马拉维 Malawi',
    'MYS' => '马来西亚 Malaysia',
    'MLI' => '马里 Mali',
    'MKD' => '前南马其顿 MACEDONIA,THE FORMER YUGOSLAV REPUBLIC OF',
    'MHL' => '马绍尔群岛 Marshall Islands',
    'MTQ' => '马提尼克 Martinique',
    'MYT' => '马约特 Mayotte',
    'MUS' => '毛里求斯 Mauritius',
    'MRT' => '毛里塔尼亚 Mauritania',
    'USA' => '美国 United States',
    'ASM' => '美属萨摩亚 American Samoa',
    'UMI' => '美国本土外小岛屿United States Minor Outlying Islands',
    'VIR' => '美属维尔京群岛 United States Virgin Is - lands',
    'MNG' => '蒙古 Mongolia',
    'MSR' => '蒙特塞拉特 Montserrat',
    'BGD' => '孟加拉国 Bangladesh',
    'PER' => '秘鲁 Peru',
    'FSM' => '密克罗尼西亚联邦 Micronesia，Federated states of',
    'MMR' => '缅甸 Myanmar',
    'MDA' => '摩尔多瓦 Moldova',
    'MAR' => '摩洛哥 Morocco',
    'MCO' => '摩纳哥 Monaco',
    'MOZ' => '莫桑比克 Mozambique',
    'MEX' => '墨西哥 Mexico',
    'NAM' => '纳米比亚 Namibia',
    'ZAF' => '南非 South Africa',
    'ATA' => '南极洲 Antarctica',
    'SGS' => '南乔治亚岛和南桑德韦奇岛 South Georgia and South Sandwich Islands',
    'NRU' => '瑙鲁 Nauru',
    'NPL' => '尼泊尔 Nepal',
    'NIC' => '尼加拉瓜 Nicaragua',
    'NER' => '尼日尔 Niger',
    'NGA' => '尼日利亚 Nigeria',
    'NIU' => '纽埃 Niue',
    'NOR' => '挪威 Norway',
    'NFK' => '诺福克岛 Norfolk Island',
    'PCN' => '皮特凯恩 Pitcairn',
    'PRT' => '葡萄牙 Portugal',
    'JPN' => '日本 Japan',
    'SWE' => '瑞典 Sweden',
    'CHE' => '瑞士 Switzerland',
    'SLV' => '萨尔瓦多 El Salvador',
    'SLE' => '塞拉利昂 Sierra leone',
    'SEN' => '塞内加尔 Senegal',
    'CYP' => '塞浦路斯 Cyprus',
    'SYC' => '塞舌尔 Seychells',
    'SAU' => '沙竺阿拉伯 Saudi Arabia',
    'CXR' => '圣诞岛 Christmas Island',
    'STP' => '圣多美和普林西比 Sao Tome and Principe',
    'SHN' => '圣赫勒拿 Saint helena',
    'KNA' => '圣基茨和尼维斯 Saint Kitts and nevis',
    'LCA' => '圣卢西亚 Saint lucia',
    'SMR' => '圣马力诺 San Marion',
    'SPM' => '圣皮埃尔和密克隆 Saint Pierre and Miquelon',
    'VCT' => '圣文森特和格林纳丁斯 Saint Vincent and the Grenadines',
    'LKA' => '斯里兰卡 Sri Lanka',
    'SVK' => '斯洛伐克 Slovakia',
    'SVN' => '斯洛文尼亚 Slovenia',
    'SJM' => '斯瓦尔巴岛和扬马延岛 Svalbard and jan Mayen Islands',
    'SWZ' => '斯威士兰 Swaziland',
    'SDN' => '苏丹 Sudan',
    'SUR' => '苏里南 Suriname',
    'SOM' => '索马里 Somalia',
    'SLB' => '所罗门群岛 Solomon Islands',
    'TJK' => '塔吉克斯坦 Tajikistan',
    'THA' => '泰国 Thailand',
    'TZA' => '坦桑尼亚 Tanzania',
    'TON' => '汤加 Tonga',
    'TCA' => '特克斯科斯群岛 Turks and Caicos Islands',
    'TTO' => '特立尼达和多巴哥 Trinidad and Tobago',
    'TUN' => '突尼斯 Tunisia',
    'TUV' => '图瓦卢 Tuvalu',
    'TUR' => '土耳其 Turkey',
    'TKM' => '土库曼斯坦 Turkmenistan',
    'TKL' => '托克劳 Tokelau',
    'WLF' => '瓦利斯和富图纳 Wallis and Futuna',
    'VUT' => '瓦努阿图 Vanuatu',
    'GTM' => '危地马拉 Guatemala',
    'VEN' => '委内瑞拉 Venezuela',
    'BRN' => '文莱 Brunei Darussalam',
    'UGA' => '乌干达 Uganda',
    'UKR' => '乌克兰 Ukraine',
    'URY' => '乌拉圭 Uruguay',
    'UZB' => '乌兹别克斯坦 Uzbekistan',
    'ESP' => '西班牙 Spain',
    'ESH' => '西撒哈拉 Western Sahara',
    'WSM' => '萨摩亚 Samoa',
    'GRC' => '希腊 Greece',
    'HKG' => '香港 Hong Kong',
    'SGP' => '新加坡 Singapore',
    'NCL' => '新喀里多尼亚 New Caledonia',
    'NZL' => '新西兰 New Zealand',
    'HUN' => '匈牙利 Hungary',
    'SYR' => '叙利亚 Syria',
    'JAM' => '牙买加 Jamaica',
    'ARM' => '亚美尼亚 Armenia',
    'YEM' => '也门 Yemen',
    'IRQ' => '伊拉克 Iraq',
    'IRN' => '伊朗 Iran',
    'ISR' => '以色列 Israel',
    'ITA' => '意大利 Italy',
    'IND' => '印度 India',
    'IDN' => '印度尼西亚 Indonesia',
    'GBR' => '英国 United Kingdom',
    'VGB' => '英属维尔京群岛 British Virgin Islands',
    'IOT' => '英属印度洋领地 British indian Ocean Territory',
    'JOR' => '约旦 Jordan',
    'VNM' => '越南 Viet Nam',
    'ZMB' => '赞比亚 Zambia',
    'TCD' => '乍得 Chad',
    'GIB' => '直布罗陀 Gibraltar',
    'CHL' => '智利 Chile',
    'CAF' => '中非 Central Africa',
    'CHN' => '中国 China',
    'TWN' => '中国台湾 Taiwan,China',
    'SRB' => '塞尔维亚  SERBIA',
    'MNE' => '黑山  MONTENEGRO'
);

*/

