<?php

    $standard = Mage::getModel('yjpay/payment');//调用工具

    $_countries = Mage::getResourceModel('directory/country_collection')
    ->loadData()
    ->toOptionArray(false);    
    
    $session = Mage::getSingleton('checkout/session');
    $_order = Mage::getModel('sales/order');
    $_order->loadByIncrementId($session->getLastRealOrderId());
    $shopAll = $_order->getAllItems();  //购物车列表
    
   //$prs = $standard->getFormFields();
    $prs = $standard->getFormFields();

    $uri = $standard->getYjpayUrl();
    $html = '<body onLoad="document.dinpayForm.submit();"><form name="dinpayForm" method="post" action="'.$uri.'" target="submitIframe">';
    foreach($prs as $k => $v){
        $html .='<input type="hidden" name="'.$k.'" value="'.htmlentities($v,ENT_QUOTES,"UTF-8").'"/>';
    }
    $html.= '</form><iframe src="" width="100%" height="500px"  name="submitIframe"  frameborder=0 scrolling="auto" />abc</iframe></body>';
    echo $html;

    ?>
